### ISSUE TITLE
Issue with Parent Ite,

### ISSUE THREAD

**Issue by adv-fjpko** [MWDelaney/sage-bootstrap4-navwalker#18]
So I Installed https://github.com/MWDelaney/sage-bootstrap4-navwalker 1 and whenever I have a parent element with sub-menu items, the parent menu item is not really clickable, it shows it has a URL but when you click on it instead of taking you to that URL it just opens the dropdown sub-menu since it adds the class "show" which makes it impossible to click to the parent URL to be clickable. Whenever I take off the sub-menu items it then becomes clickable. Do you have any suggestions on how to fix this?

**Comment by MWDelaney** [comment]
This is by design. Bootstrap's usability principles for dropdowns suggest a menu item should either be a navigation item, or a dropdown trigger, not both, so this navwalker implements that principle.
